### ISSUE TITLE
Patching fails for 11.2 version due to emocmrsp

### ISSUE THREAD

**Issue by ukalshetty** [iarsov/ansible-orapatch#8]
Ivica,
I was trying the module to patch 11.2.0.4 database home and is failing with the below error.
As per MOS 2161861.1 this is now deprecated and ocmrsp is no longer required.

Thu 29 Oct 2020 03:45:47 AM EDT	ORACLE_HOME set to to '/u01/app/oracle/product/11.2.0.4/dbhome_1'
Thu 29 Oct 2020 03:45:47 AM EDT	command: /u01/app/oracle/product/11.2.0.4/dbhome_1/OPatch/ocm/bin/emocmrsp -no_banner -output /tmp/orapatch_ocm_2020-10-29_03-45-47AM.rsp
Thu 29 Oct 2020 03:45:47 AM EDT	The command was not found or was not executable: /u01/app/oracle/product/11.2.0.4/dbhome_1/OPatch/ocm/bin/emocmrsp.
Thu 29 Oct 2020 03:45:47 AM EDT	ExceptionPexpect
Thu 29 Oct 2020 03:45:47 AM EDT	Module fail: Traceback (most recent call last):
  File "/tmp/ansible_orapatch_payload_M_Qgfy/ansible_orapatch_payload.zip/ansible/modules/orapatch.py", line 2051, in main
  File "/tmp/ansible_orapatch_payload_M_Qgfy/ansible_orapatch_payload.zip/ansible/modules/orapatch.py", line 461, in __init__
  File "/tmp/ansible_orapatch_payload_M_Qgfy/ansible_orapatch_payload.zip/ansible/modules/orapatch.py", line 507, in gen_ocm_file
  File "/tmp/ansible_orapatch_payload_M_Qgfy/ansible_orapatch_payload.zip/ansible/modules/orapatch.py", line 622, in run_os_command
  File "/usr/lib/python2.7/site-packages/pexpect.py", line 221, in run
    child = spawn(command, timeout=timeout, maxread=2000, logfile=logfile, cwd=cwd, env=env)
  File "/usr/lib/python2.7/site-packages/pexpect.py", line 429, in __init__
    self._spawn (command, args)
  File "/usr/lib/python2.7/site-packages/pexpect.py", line 516, in _spawn
    raise ExceptionPexpect ('The command was not found or was not executable: %s.' % self.command)
ExceptionPexpect: The command was not found or was not executable: /u01/app/oracle/product/11.2.0.4/dbhome_1/OPatch/ocm/bin/emocmrsp.

Would changing the system parameter to include version 11 as a supported version help in fixing the error?

Thanks,
Umesh

**Comment by ukalshetty** [comment]
I went ahead and made 11 as a supported version in the parameters along with some tweaks in the code. It all went fine only to fail with the below error again.
I have tried this 4-5 times now without any progress. I see that the patch is applied to OH successfully but the dictionary is not updated.

==============================================
FUNC => PATCH_OH
==============================================
Thu 29 Oct 2020 07:12:30 AM EDT	ORACLE_HOME set to to '/u01/app/oracle/product/11.2.0.4/dbhome_1'
Thu 29 Oct 2020 07:12:30 AM EDT	command: /u01/app/oracle/product/11.2.0.4/dbhome_1/OPatch/opatch apply -silent /home/oracle/Downloads/31103343
Thu 29 Oct 2020 07:29:07 AM EDT	'ascii' codec can't decode byte 0xe2 in position 15173: ordinal not in range(128)
Thu 29 Oct 2020 07:29:07 AM EDT	UnicodeDecodeError
Thu 29 Oct 2020 07:29:07 AM EDT	Module fail: Traceback (most recent call last):
  File "/tmp/ansible_orapatch_payload_dhMXlr/ansible_orapatch_payload.zip/ansible/modules/orapatch.py", line 2053, in main
  File "/tmp/ansible_orapatch_payload_dhMXlr/ansible_orapatch_payload.zip/ansible/modules/orapatch.py", line 1915, in patchprocess_main
  File "/tmp/ansible_orapatch_payload_dhMXlr/ansible_orapatch_payload.zip/ansible/modules/orapatch.py", line 835, in patch_oh
  File "/tmp/ansible_orapatch_payload_dhMXlr/ansible_orapatch_payload.zip/ansible/modules/orapatch.py", line 1125, in patch_db_oh
  File "/tmp/ansible_orapatch_payload_dhMXlr/ansible_orapatch_payload.zip/ansible/modules/orapatch.py", line 637, in run_os_command
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 15173: ordinal not in range(128)

Any help is much appreciated.

Thanks.

**Comment by ukalshetty** [comment]
I have found the solution to this. This was failing at the below statement  while converting to str.

logger(str (v_output), True)

After removing the str function this has succeeded and completed the patching process.

Please let me know this is not a correct approach.

Thanks,
Umesh
